/* ============================================================
   QR Creator
   Vanilla JS, no dependencies, nothing saved anywhere — same rule as
   every other tool on this site (see AI_BUILD_BRIEF.md). This file
   is everything EXCEPT the actual QR math (see qr-creator-engine.js,
   loaded first): content-type payload builders, module styling,
   canvas/SVG rendering, logo overlay, and all the DOM wiring.
   ------------------------------------------------------------
   WHY THIS NEEDS NO BACKEND AT ALL: unlike Food Worth, Crypto Radar,
   or Market Radar, this tool never calls a Cloudflare Worker and
   never will need one — there's no external data to fetch and no key
   to protect. Encoding, styling, and any logo image you upload all
   happen locally in your own browser; nothing is ever sent anywhere.
   That's not a missing feature, it's the correct architecture for
   what this tool does — see QR_CREATOR_NOTES.md.

   ARCHITECTURE: qr-creator-engine.js turns text into a matrix of
   true/false modules plus which ones are "function" modules (finder/
   timing/alignment/format/version/dark-module). Everything in THIS
   file turns that matrix into pixels: classifyModule() sorts each
   dark module into finder-frame / finder-ball / body so they can be
   styled independently (the three-eyes-plus-body split every
   commercial "styled QR" generator uses), buildRenderPlan() turns
   that into a flat list of shapes in MODULE-space coordinates (not
   pixels), and renderPlanToCanvas()/renderPlanToSVGString() are the
   only two places that know about actual pixels — both consume the
   exact same plan, so the live preview, the PNG download, and the
   SVG download can never visually drift apart from each other.

   Every shape geometry choice below (dot radius, corner-rounding
   radius, eye-style safety) was verified empirically, not assumed:
   matrices were generated by the real engine, rasterized as real
   circles/rounded-rects (not approximated), and decoded with an
   independent QR reader across dots+circle-eyes, square+circle-eyes,
   and rounded+rounded-eyes combinations, on real URL/WiFi/vCard
   payloads, before these became the shipped defaults.
   ============================================================ */

console.info('[QR Creator] script build: 2026-09-18-v1');

/* ================= CONFIG =================
   Everything a layperson might want to retune lives here. See the
   in-page Settings reference section (and its companion .xlsx) for
   the same table outside the code. */

const DEFAULT_FG = '#1F6F5C';      // Reysourcez brand teal
const DEFAULT_BG = '#FFFFFF';
const DEFAULT_ECC_LEVEL = 'M';     // L/M/Q/H — auto-bumped to H the moment a logo is added
const LOGO_FORCE_ECC = 'H';
const LOGO_SIZE_MIN_PCT = 12;
const LOGO_SIZE_MAX_PCT = 32;
const LOGO_SIZE_DEFAULT_PCT = 22;  // ~22% of QR width ≈ ~5% of module AREA covered — safely under level H's 30% recovery budget even before the backing plate is counted
const QUIET_ZONE_DEFAULT = 4;      // modules — the spec's own recommended minimum
const QUIET_ZONE_MIN = 2;
const QUIET_ZONE_MAX = 8;
const PNG_EXPORT_PX_DEFAULT = 1000;
const PNG_EXPORT_PX_MIN = 200;
const PNG_EXPORT_PX_MAX = 4000;
const PREVIEW_PX = 320;            // fixed on-screen preview size; export size is independent

/* ================= CONTENT-TYPE PAYLOAD BUILDERS =================
   WIFI: syntax matches the de-facto standard both Android and iOS
   camera apps parse (documented by the ZXing project). vCard uses
   3.0 specifically, not 4.0 — 3.0 is what scans reliably into both
   iOS and Android's native "add contact" flow; 4.0 has real parser
   gaps on older devices for QR-scanned cards specifically. Both
   verified against current documentation while building this, not
   assumed from memory. */

function escapeFieldGeneric(s, extra) {
  var out = String(s == null ? '' : s).replace(/\\/g, '\\\\');
  (extra || [';', ',', ':']).forEach(function (ch) { out = out.split(ch).join('\\' + ch); });
  return out;
}

function buildWifiPayload(f) {
  f = f || {};
  var type = f.encryption || 'WPA'; // 'WPA' | 'WEP' | 'nopass'
  var parts = ['WIFI:T:' + type + ';S:' + escapeFieldGeneric(f.ssid)];
  if (type !== 'nopass') parts.push('P:' + escapeFieldGeneric(f.password));
  if (f.hidden) parts.push('H:true');
  return parts.join(';') + ';;';
}

function buildVCardPayload(f) {
  f = f || {};
  var esc = function (s) { return escapeFieldGeneric(s, [';', ',']).replace(/\n/g, '\\n'); };
  var lines = ['BEGIN:VCARD', 'VERSION:3.0'];
  lines.push('N:' + esc(f.lastName) + ';' + esc(f.firstName) + ';;;');
  var fn = [f.firstName, f.lastName].filter(Boolean).join(' ').trim() || f.org || '';
  lines.push('FN:' + esc(fn));
  if (f.org) lines.push('ORG:' + esc(f.org));
  if (f.title) lines.push('TITLE:' + esc(f.title));
  if (f.phone) lines.push('TEL;TYPE=CELL,VOICE:' + f.phone);
  if (f.email) lines.push('EMAIL;TYPE=INTERNET:' + f.email);
  if (f.url) lines.push('URL:' + f.url);
  if (f.address) lines.push('ADR;TYPE=WORK:;;' + esc(f.address) + ';;;;');
  if (f.note) lines.push('NOTE:' + esc(f.note));
  lines.push('END:VCARD');
  return lines.join('\r\n');
}

function buildMailtoPayload(f) {
  f = f || {};
  var params = [];
  if (f.subject) params.push('subject=' + encodeURIComponent(f.subject));
  if (f.body) params.push('body=' + encodeURIComponent(f.body));
  return 'mailto:' + (f.to || '') + (params.length ? '?' + params.join('&') : '');
}
function buildTelPayload(f) { return 'tel:' + String((f && f.number) || '').replace(/[^\d+]/g, ''); }
function buildSmsPayload(f) {
  f = f || {};
  var n = String(f.number || '').replace(/[^\d+]/g, '');
  return 'sms:' + n + (f.body ? '?body=' + encodeURIComponent(f.body) : '');
}

/* ================= MODULE CLASSIFICATION + RENDER PLAN =================
   Shared, resolution-independent shape geometry — see this file's own
   header comment for why the same plan drives canvas, SVG, and the
   live preview identically. Coordinates throughout are in MODULE
   units (0..size); renderPlanToCanvas/renderPlanToSVGString are the
   only two places pixel scale or quiet-zone offset ever get applied. */

function classifyModule(x, y, size) {
  var boxes = [[0, 0], [size - 7, 0], [0, size - 7]];
  for (var i = 0; i < boxes.length; i++) {
    var dx = x - boxes[i][0], dy = y - boxes[i][1];
    if (dx >= 0 && dx <= 6 && dy >= 0 && dy <= 6) {
      if (dx === 0 || dx === 6 || dy === 0 || dy === 6) return 'finder-frame';
      if (dx >= 2 && dx <= 4 && dy >= 2 && dy <= 4) return 'finder-ball';
      return 'finder-gap'; // the light ring between frame and ball; never dark, never drawn
    }
  }
  return 'body';
}

function roundedRectPath(x, y, w, h, tl, tr, br, bl) {
  tl = Math.max(0, Math.min(tl, w / 2, h / 2));
  tr = Math.max(0, Math.min(tr, w / 2, h / 2));
  br = Math.max(0, Math.min(br, w / 2, h / 2));
  bl = Math.max(0, Math.min(bl, w / 2, h / 2));
  return 'M' + (x + tl) + ',' + y
    + ' L' + (x + w - tr) + ',' + y + ' A' + tr + ',' + tr + ' 0 0 1 ' + (x + w) + ',' + (y + tr)
    + ' L' + (x + w) + ',' + (y + h - br) + ' A' + br + ',' + br + ' 0 0 1 ' + (x + w - br) + ',' + (y + h)
    + ' L' + (x + bl) + ',' + (y + h) + ' A' + bl + ',' + bl + ' 0 0 1 ' + x + ',' + (y + h - bl)
    + ' L' + x + ',' + (y + tl) + ' A' + tl + ',' + tl + ' 0 0 1 ' + (x + tl) + ',' + y + ' Z';
}

function bodyDarkNeighbor(matrix, size, x, y, dx, dy) {
  var nx = x + dx, ny = y + dy;
  if (nx < 0 || ny < 0 || nx >= size || ny >= size) return false;
  if (!matrix[ny][nx]) return false;
  return classifyModule(nx, ny, size) === 'body';
}

// options: { bodyStyle: 'square'|'dots'|'rounded', dotScale, roundedScale,
//   eyeFrameStyle, eyeBallStyle: 'square'|'rounded'|'circle',
//   fg, bg, eyeFrameColor, eyeBallColor }
// dotScale 0.46 and the eye-ring radii below were the exact values
// empirically scan-tested (see this file's header) — safe to nudge
// slightly but treat as verified defaults, not arbitrary numbers.
function buildRenderPlan(matrix, size, options) {
  var o = options || {};
  var bodyStyle = o.bodyStyle || 'square';
  var dotScale = o.dotScale != null ? o.dotScale : 0.46;
  var roundedScale = o.roundedScale != null ? o.roundedScale : 0.3;
  var eyeFrameStyle = o.eyeFrameStyle || 'square';
  var eyeBallStyle = o.eyeBallStyle || 'square';
  var fg = o.fg || DEFAULT_FG;
  var bg = o.bg || DEFAULT_BG;
  var eyeFrameColor = o.eyeFrameColor || fg;
  var eyeBallColor = o.eyeBallColor || fg;

  var shapes = [];
  var drawnEyeBoxes = {};

  function addEyeShapes(originX, originY) {
    var key = originX + ',' + originY;
    if (drawnEyeBoxes[key]) return;
    drawnEyeBoxes[key] = true;
    // Draw outer solid, then a background-colored "hole" on top --
    // valid because this tool only offers flat solid colors; would
    // need revisiting if a gradient/pattern fill is ever added (see
    // QR_CREATOR_NOTES.md's KIV list).
    if (eyeFrameStyle === 'circle') {
      shapes.push({ type: 'circle', cx: originX + 3.5, cy: originY + 3.5, r: 3.5, fill: eyeFrameColor });
      shapes.push({ type: 'circle', cx: originX + 3.5, cy: originY + 3.5, r: 2.5, fill: bg });
    } else if (eyeFrameStyle === 'rounded') {
      shapes.push({ type: 'path', d: roundedRectPath(originX, originY, 7, 7, 1.8, 1.8, 1.8, 1.8), fill: eyeFrameColor });
      shapes.push({ type: 'path', d: roundedRectPath(originX + 1, originY + 1, 5, 5, 1.2, 1.2, 1.2, 1.2), fill: bg });
    } else {
      shapes.push({ type: 'rect', x: originX, y: originY, w: 7, h: 7, fill: eyeFrameColor });
      shapes.push({ type: 'rect', x: originX + 1, y: originY + 1, w: 5, h: 5, fill: bg });
    }
    if (eyeBallStyle === 'circle') {
      shapes.push({ type: 'circle', cx: originX + 3.5, cy: originY + 3.5, r: 1.55, fill: eyeBallColor });
    } else if (eyeBallStyle === 'rounded') {
      shapes.push({ type: 'path', d: roundedRectPath(originX + 2, originY + 2, 3, 3, 0.9, 0.9, 0.9, 0.9), fill: eyeBallColor });
    } else {
      shapes.push({ type: 'rect', x: originX + 2, y: originY + 2, w: 3, h: 3, fill: eyeBallColor });
    }
  }

  for (var y = 0; y < size; y++) {
    for (var x = 0; x < size; x++) {
      if (!matrix[y][x]) continue;
      var cls = classifyModule(x, y, size);
      if (cls === 'finder-frame' || cls === 'finder-ball') {
        addEyeShapes(x < 7 ? 0 : size - 7, y < 7 ? 0 : size - 7);
        continue;
      }
      if (bodyStyle === 'dots') {
        shapes.push({ type: 'circle', cx: x + 0.5, cy: y + 0.5, r: dotScale, fill: fg });
      } else if (bodyStyle === 'rounded') {
        var up = bodyDarkNeighbor(matrix, size, x, y, 0, -1);
        var down = bodyDarkNeighbor(matrix, size, x, y, 0, 1);
        var left = bodyDarkNeighbor(matrix, size, x, y, -1, 0);
        var right = bodyDarkNeighbor(matrix, size, x, y, 1, 0);
        var r = roundedScale;
        shapes.push({ type: 'path', d: roundedRectPath(x, y, 1, 1, (up || left) ? 0 : r, (up || right) ? 0 : r, (down || right) ? 0 : r, (down || left) ? 0 : r), fill: fg });
      } else {
        shapes.push({ type: 'rect', x: x, y: y, w: 1, h: 1, fill: fg });
      }
    }
  }
  return { size: size, bg: bg, shapes: shapes };
}

/* ================= CANVAS RENDERING ================= */

function renderPlanToCanvas(canvas, plan, pxPerModule, quietZoneModules) {
  var totalPx = (plan.size + quietZoneModules * 2) * pxPerModule;
  canvas.width = totalPx;
  canvas.height = totalPx;
  var ctx = canvas.getContext('2d');
  ctx.fillStyle = plan.bg;
  ctx.fillRect(0, 0, totalPx, totalPx);
  var offset = quietZoneModules * pxPerModule;

  plan.shapes.forEach(function (s) {
    ctx.fillStyle = s.fill;
    if (s.type === 'rect') {
      ctx.fillRect(offset + s.x * pxPerModule, offset + s.y * pxPerModule, s.w * pxPerModule, s.h * pxPerModule);
    } else if (s.type === 'circle') {
      ctx.beginPath();
      ctx.arc(offset + s.cx * pxPerModule, offset + s.cy * pxPerModule, s.r * pxPerModule, 0, Math.PI * 2);
      ctx.fill();
    } else if (s.type === 'path') {
      ctx.save();
      ctx.translate(offset, offset);
      ctx.scale(pxPerModule, pxPerModule);
      ctx.fill(new Path2D(s.d));
      ctx.restore();
    }
  });
  return ctx;
}

function renderPlanToSVGString(plan, pxPerModule, quietZoneModules) {
  var totalPx = (plan.size + quietZoneModules * 2) * pxPerModule;
  var offset = quietZoneModules * pxPerModule;
  var body = plan.shapes.map(function (s) {
    if (s.type === 'rect') {
      return '<rect x="' + (offset + s.x * pxPerModule).toFixed(2) + '" y="' + (offset + s.y * pxPerModule).toFixed(2)
        + '" width="' + (s.w * pxPerModule).toFixed(2) + '" height="' + (s.h * pxPerModule).toFixed(2) + '" fill="' + s.fill + '"/>';
    }
    if (s.type === 'circle') {
      return '<circle cx="' + (offset + s.cx * pxPerModule).toFixed(2) + '" cy="' + (offset + s.cy * pxPerModule).toFixed(2)
        + '" r="' + (s.r * pxPerModule).toFixed(2) + '" fill="' + s.fill + '"/>';
    }
    // path: translate+scale via a <g transform>, one per shape is fine at these counts
    return '<g transform="translate(' + offset + ',' + offset + ') scale(' + pxPerModule + ')"><path d="' + s.d + '" fill="' + s.fill + '"/></g>';
  }).join('');
  return '<svg xmlns="http://www.w3.org/2000/svg" width="' + totalPx + '" height="' + totalPx + '" viewBox="0 0 ' + totalPx + ' ' + totalPx + '">'
    + '<rect width="' + totalPx + '" height="' + totalPx + '" fill="' + plan.bg + '"/>' + body + '</svg>';
}

/* ================= LOGO OVERLAY =================
   Drawn on top of the finished canvas — never touches the matrix or
   the encoder. Standard, proven approach (what every consumer "QR +
   logo" generator does): encode at high error correction, then
   visually cover the center. Width-based sizing keeps this safe by
   construction — area scales with the SQUARE of the width fraction,
   so even a generous-looking 32%-wide logo only covers ~10% of the
   matrix area, comfortably under level H's 30% recovery budget, with
   the backing plate included. */

function drawLogoOverlay(canvas, logoImg, sizePct, shape) {
  var ctx = canvas.getContext('2d');
  var total = canvas.width;
  var logoPx = total * (sizePct / 100);
  var plateInset = logoPx * 0.14; // backing plate slightly larger than the logo itself
  var plateSize = logoPx + plateInset * 2;
  var cx = total / 2, cy = total / 2;

  ctx.save();
  ctx.fillStyle = '#FFFFFF';
  if (shape === 'circle') {
    ctx.beginPath();
    ctx.arc(cx, cy, plateSize / 2, 0, Math.PI * 2);
    ctx.fill();
  } else {
    var r = shape === 'rounded' ? plateSize * 0.18 : 0;
    ctx.beginPath();
    ctx.fill(new Path2D(roundedRectPathPx(cx - plateSize / 2, cy - plateSize / 2, plateSize, plateSize, r)));
  }
  ctx.restore();

  var drawW = logoPx, drawH = logoPx;
  if (logoImg.naturalWidth && logoImg.naturalHeight) {
    var ratio = logoImg.naturalWidth / logoImg.naturalHeight;
    if (ratio > 1) drawH = logoPx / ratio; else drawW = logoPx * ratio;
  }
  ctx.drawImage(logoImg, cx - drawW / 2, cy - drawH / 2, drawW, drawH);
}

// Pixel-space rounded-rect path (separate from the module-space one
// above — logo placement works directly in canvas pixels, not
// modules, since it's independent of the QR grid).
function roundedRectPathPx(x, y, w, h, r) {
  r = Math.max(0, Math.min(r, w / 2, h / 2));
  return 'M' + (x + r) + ',' + y + ' L' + (x + w - r) + ',' + y + ' A' + r + ',' + r + ' 0 0 1 ' + (x + w) + ',' + (y + r)
    + ' L' + (x + w) + ',' + (y + h - r) + ' A' + r + ',' + r + ' 0 0 1 ' + (x + w - r) + ',' + (y + h)
    + ' L' + (x + r) + ',' + (y + h) + ' A' + r + ',' + r + ' 0 0 1 ' + x + ',' + (y + h - r)
    + ' L' + x + ',' + (y + r) + ' A' + r + ',' + r + ' 0 0 1 ' + (x + r) + ',' + y + ' Z';
}

/* ================= CONTENT-TYPE TABS ================= */

const CONTENT_TYPES = ['text', 'wifi', 'vcard', 'email', 'phone'];
let activeContentType = 'text';
let logoImageEl = null; // the loaded <img>, once a logo's been chosen

function gatherContentPayload() {
  switch (activeContentType) {
    case 'wifi':
      return buildWifiPayload({
        ssid: val('qr-wifi-ssid'), password: val('qr-wifi-password'),
        encryption: val('qr-wifi-encryption'), hidden: document.getElementById('qr-wifi-hidden').checked,
      });
    case 'vcard':
      return buildVCardPayload({
        firstName: val('qr-vcard-first'), lastName: val('qr-vcard-last'), org: val('qr-vcard-org'),
        title: val('qr-vcard-title'), phone: val('qr-vcard-phone'), email: val('qr-vcard-email'),
        url: val('qr-vcard-url'), address: val('qr-vcard-address'),
      });
    case 'email':
      return buildMailtoPayload({ to: val('qr-email-to'), subject: val('qr-email-subject'), body: val('qr-email-body') });
    case 'phone':
      return val('qr-phone-mode') === 'sms'
        ? buildSmsPayload({ number: val('qr-phone-number'), body: val('qr-phone-sms-body') })
        : buildTelPayload({ number: val('qr-phone-number') });
    default:
      return val('qr-text-input');
  }
}
function val(id) { var el = document.getElementById(id); return el ? el.value.trim() : ''; }

function switchContentType(type) {
  activeContentType = type;
  document.querySelectorAll('[data-content-type]').forEach(function (t) { t.classList.toggle('is-active', t.dataset.contentType === type); });
  document.querySelectorAll('[data-content-panel]').forEach(function (p) { p.hidden = p.dataset.contentPanel !== type; });
  updatePhoneModeVisibility();
  updateWifiPasswordVisibility();
  recalculate();
}

// Both of these need to react whenever their OWN dropdown changes
// too, not just when the tab is first opened — wired as dedicated
// listeners in init(), since the generic "any field in
// #qr-content-panels re-runs recalculate()" listener has no reason
// to also know about this tab-internal show/hide behavior.
function updatePhoneModeVisibility() {
  document.getElementById('qr-phone-sms-body').closest('label').hidden = val('qr-phone-mode') !== 'sms';
}
function updateWifiPasswordVisibility() {
  document.getElementById('qr-wifi-password').closest('label').hidden = val('qr-wifi-encryption') === 'nopass';
}

/* ================= STATE + RECALCULATE ================= */

let lastEncoded = null;

function currentStyleOptions() {
  return {
    bodyStyle: document.querySelector('[name="qr-body-style"]:checked').value,
    eyeFrameStyle: document.querySelector('[name="qr-eye-frame-style"]:checked').value,
    eyeBallStyle: document.querySelector('[name="qr-eye-ball-style"]:checked').value,
    fg: document.getElementById('qr-fg-color').value,
    bg: document.getElementById('qr-bg-color').value,
  };
}

function updatePctBadges() {
  // no-op placeholder kept for symmetry with other tools' small live-badge helpers
}

function recalculate() {
  const text = gatherContentPayload();
  const statusEl = document.getElementById('qr-status');
  const hasLogo = !!logoImageEl;
  let eccLevel = document.getElementById('qr-ecc-level').value;
  if (hasLogo) eccLevel = LOGO_FORCE_ECC;

  if (!text) {
    document.getElementById('qr-preview-wrap').classList.add('is-empty');
    statusEl.textContent = 'Fill in the fields above to generate your code.';
    statusEl.classList.remove('is-error');
    document.querySelectorAll('.qr-download-btn').forEach(function (b) { b.disabled = true; });
    lastEncoded = null;
    return;
  }

  let encoded;
  try {
    encoded = QRCreatorEngine.encode(text, { eccLevel: eccLevel, boostEcl: !hasLogo });
  } catch (err) {
    document.getElementById('qr-preview-wrap').classList.add('is-empty');
    statusEl.textContent = err.message || 'Could not generate a code for this content.';
    statusEl.classList.add('is-error');
    document.querySelectorAll('.qr-download-btn').forEach(function (b) { b.disabled = true; });
    lastEncoded = null;
    return;
  }
  lastEncoded = encoded;
  document.getElementById('qr-preview-wrap').classList.remove('is-empty');
  document.querySelectorAll('.qr-download-btn').forEach(function (b) { b.disabled = false; });

  const quietZone = Number(document.getElementById('qr-quiet-zone').value) || QUIET_ZONE_DEFAULT;
  const plan = buildRenderPlan(encoded.matrix, encoded.size, currentStyleOptions());
  const pxPerModule = PREVIEW_PX / (encoded.size + quietZone * 2);
  const canvas = document.getElementById('qr-preview-canvas');
  renderPlanToCanvas(canvas, plan, pxPerModule, quietZone);

  if (hasLogo) {
    const shape = document.querySelector('[name="qr-logo-shape"]:checked').value;
    const sizePct = Number(document.getElementById('qr-logo-size').value) || LOGO_SIZE_DEFAULT_PCT;
    drawLogoOverlay(canvas, logoImageEl, sizePct, shape);
  }

  statusEl.classList.remove('is-error');
  statusEl.textContent = 'Version ' + encoded.version + ' · ' + encoded.size + '\u00d7' + encoded.size + ' modules · '
    + 'Error correction ' + encoded.level + (hasLogo ? ' (raised automatically for the logo)' : '') + '.';
}

/* ================= LOGO UPLOAD ================= */

function handleLogoFile(file) {
  if (!file) return;
  const reader = new FileReader();
  reader.onload = function () {
    const img = new Image();
    img.onload = function () {
      logoImageEl = img;
      document.getElementById('qr-logo-controls').hidden = false;
      document.getElementById('qr-logo-preview').src = reader.result;
      document.getElementById('qr-logo-preview').hidden = false;
      document.getElementById('qr-ecc-level').value = LOGO_FORCE_ECC;
      document.getElementById('qr-ecc-level').disabled = true;
      document.getElementById('qr-ecc-forced-note').hidden = false;
      recalculate();
    };
    img.onerror = function () { document.getElementById('qr-logo-status').textContent = 'Could not read that image — try a different file.'; };
    img.src = reader.result;
  };
  reader.readAsDataURL(file);
}
function removeLogo() {
  logoImageEl = null;
  document.getElementById('qr-logo-controls').hidden = true;
  document.getElementById('qr-logo-preview').hidden = true;
  document.getElementById('qr-logo-input').value = '';
  document.getElementById('qr-ecc-level').disabled = false;
  document.getElementById('qr-ecc-forced-note').hidden = true;
  recalculate();
}

/* ================= DOWNLOADS ================= */

function downloadDataUrl(filename, dataUrl) {
  const a = document.createElement('a');
  a.href = dataUrl; a.download = filename;
  document.body.appendChild(a); a.click(); a.remove();
}

function downloadPNG() {
  if (!lastEncoded) return;
  const exportPx = Number(document.getElementById('qr-export-size').value) || PNG_EXPORT_PX_DEFAULT;
  const quietZone = Number(document.getElementById('qr-quiet-zone').value) || QUIET_ZONE_DEFAULT;
  const plan = buildRenderPlan(lastEncoded.matrix, lastEncoded.size, currentStyleOptions());
  const pxPerModule = exportPx / (lastEncoded.size + quietZone * 2);
  const offscreen = document.createElement('canvas');
  renderPlanToCanvas(offscreen, plan, pxPerModule, quietZone);
  if (logoImageEl) {
    const shape = document.querySelector('[name="qr-logo-shape"]:checked').value;
    const sizePct = Number(document.getElementById('qr-logo-size').value) || LOGO_SIZE_DEFAULT_PCT;
    drawLogoOverlay(offscreen, logoImageEl, sizePct, shape);
  }
  downloadDataUrl('qr-code.png', offscreen.toDataURL('image/png'));
}

function downloadSVG() {
  if (!lastEncoded) return;
  const quietZone = Number(document.getElementById('qr-quiet-zone').value) || QUIET_ZONE_DEFAULT;
  const plan = buildRenderPlan(lastEncoded.matrix, lastEncoded.size, currentStyleOptions());
  let svg = renderPlanToSVGString(plan, 10, quietZone); // 10px/module in SVG user-units — it's vector, so this only sets the viewBox scale, not the print resolution
  if (logoImageEl) {
    // Embed the logo as a base64 <image> so the SVG stays fully
    // self-contained (matches this site's "no external references"
    // rule for exported assets, same reasoning as inlined fonts/CSS
    // elsewhere on the site).
    const total = (lastEncoded.size + quietZone * 2) * 10;
    const shape = document.querySelector('[name="qr-logo-shape"]:checked').value;
    const sizePct = Number(document.getElementById('qr-logo-size').value) || LOGO_SIZE_DEFAULT_PCT;
    const logoPx = total * (sizePct / 100);
    const plateInset = logoPx * 0.14;
    const plateSize = logoPx + plateInset * 2;
    const cx = total / 2, cy = total / 2;
    let plateShape;
    if (shape === 'circle') plateShape = '<circle cx="' + cx + '" cy="' + cy + '" r="' + (plateSize / 2) + '" fill="#fff"/>';
    else plateShape = '<path d="' + roundedRectPathPx(cx - plateSize / 2, cy - plateSize / 2, plateSize, plateSize, shape === 'rounded' ? plateSize * 0.18 : 0) + '" fill="#fff"/>';
    const logoTag = '<image href="' + document.getElementById('qr-logo-preview').src + '" x="' + (cx - logoPx / 2) + '" y="' + (cy - logoPx / 2) + '" width="' + logoPx + '" height="' + logoPx + '" preserveAspectRatio="xMidYMid meet"/>';
    svg = svg.replace('</svg>', plateShape + logoTag + '</svg>');
  }
  downloadDataUrl('qr-code.svg', 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(svg));
}

/* ================= JARGON INDEX ================= */

const JARGON = [
  { term: 'Error correction level (L/M/Q/H)', def: 'How much of the code can be damaged, covered, or misprinted and still scan correctly — roughly 7% (L), 15% (M), 25% (Q), or 30% (H). Higher levels use more of the code\u2019s capacity for redundancy, which is why the same text produces a slightly bigger code at H than at L.' },
  { term: 'Version (1\u201340)', def: 'The QR spec\u2019s own term for the code\u2019s size \u2014 version 1 is the smallest (21\u00d721 modules), version 40 the largest (177\u00d7177). This tool always picks the smallest version that fits your content at the error correction level you chose.' },
  { term: 'Module', def: 'One of the small squares a QR code is built from \u2014 the actual unit of data. What you style (dots, rounded corners) are these modules, not individual pixels.' },
  { term: 'Finder pattern (the three \u201ceyes\u201d)', def: 'The three bullseye squares in the corners that let a scanner instantly recognize and orient a QR code before reading anything else. Their frame and center dot can be styled independently from the rest of the code.' },
  { term: 'Quiet zone', def: 'The blank margin required around the code\u2019s outer edge. The spec\u2019s own recommended minimum is 4 modules \u2014 shrinking it can make some scanners fail to recognize the code at all, especially printed at small sizes.' },
  { term: 'Masking', def: 'QR codes apply one of 8 fixed patterns that XOR the data to avoid large blank runs or accidental finder-pattern lookalikes in the data area \u2014 required by the spec for reliable scanning, not a visual style choice. This tool tries all 8 and keeps whichever scores best.' },
];

/* ================= INIT ================= */

let rzInitialized = false;

function init() {
  if (rzInitialized) return;
  rzInitialized = true;

  document.querySelectorAll('[data-content-type]').forEach(function (t) {
    t.addEventListener('click', function () { switchContentType(t.dataset.contentType); });
  });
  document.querySelectorAll('#qr-content-panels input, #qr-content-panels textarea, #qr-content-panels select').forEach(function (el) {
    el.addEventListener('input', recalculate);
    el.addEventListener('change', recalculate);
  });
  document.getElementById('qr-phone-mode').addEventListener('change', updatePhoneModeVisibility);
  document.getElementById('qr-wifi-encryption').addEventListener('change', updateWifiPasswordVisibility);

  document.querySelectorAll('[name="qr-body-style"], [name="qr-eye-frame-style"], [name="qr-eye-ball-style"], [name="qr-logo-shape"]').forEach(function (el) {
    el.addEventListener('change', recalculate);
  });
  document.getElementById('qr-fg-color').addEventListener('input', recalculate);
  document.getElementById('qr-bg-color').addEventListener('input', recalculate);
  document.getElementById('qr-ecc-level').addEventListener('change', recalculate);
  document.getElementById('qr-quiet-zone').addEventListener('input', recalculate);
  document.getElementById('qr-logo-size').addEventListener('input', recalculate);

  document.getElementById('qr-logo-input').addEventListener('change', function (e) { handleLogoFile(e.target.files[0]); });
  document.getElementById('qr-logo-remove').addEventListener('click', removeLogo);

  document.getElementById('qr-download-png').addEventListener('click', downloadPNG);
  document.getElementById('qr-download-svg').addEventListener('click', downloadSVG);
  document.getElementById('qr-save-pdf').addEventListener('click', function () { window.print(); });
  document.getElementById('qr-export-size').addEventListener('input', function () {
    document.getElementById('qr-export-size-display').textContent = this.value + 'px';
  });

  document.getElementById('qr-jargon').innerHTML = JARGON.map(function (g) {
    return '<details class="qr-collapsible"><summary class="qr-collapsible-summary"><h3>' + g.term + '</h3></summary>'
      + '<div class="qr-collapsible-body">' + g.def + '</div></details>';
  }).join('');

  const quickNav = document.getElementById('qr-quick-nav');
  document.querySelectorAll('.qr-quick-nav-btn[data-target]').forEach(function (btn) {
    btn.addEventListener('click', function () {
      const target = document.getElementById(btn.dataset.target);
      if (!target) return;
      target.querySelectorAll('details:not([open])').forEach(function (d) { d.open = true; });
      target.scrollIntoView({ behavior: 'smooth', block: 'start' });
    });
  });
  window.addEventListener('scroll', function () { quickNav.hidden = window.scrollY < window.innerHeight * 0.3; }, { passive: true });
  document.getElementById('qr-back-to-top').addEventListener('click', function () { window.scrollTo({ top: 0, behavior: 'smooth' }); });

  switchContentType('text');
  recalculate();
}

document.addEventListener('DOMContentLoaded', init);
